import cv2
import numpy as np

from openvino.inference_engine import IEPlugin
from openvino.inference_engine import IENetwork

class FeatureExtractor():
	
	def __init__(self, binary_path, xml_path):
		plugin = IEPlugin(device="MYRIAD")

		# read the IR generated by the Model Optimizer (.xml and .bin files)
		print("[INFO] loading models...")
		net = IENetwork(model=xml_path, weights=binary_path)

		# prepare inputs
		print("[INFO] preparing inputs...")
		self.inputBlob = next(iter(net.inputs))

		# set the default batch size as 1 and get the number of input blobs,
		# number of channels, the height, and width of the input blob
		net.batch_size = 1
		print(net.inputs[self.inputBlob].shape)

		print("[INFO] loading model to the plugin...")
		self.execNet = plugin.load(network=net, num_requests=1)
		print("[INFO] Model loaded successfully!")

	def extract(self, frame):
		"""
		Return extracted features
		"""
		return self.execNet.infer({self.inputBlob: frame})

	@staticmethod
	def preprocess_frame(frame):
		frame = cv2.resize(frame, (224, 224))
		frame = np.transpose(frame, (2,0,1))
		return frame